In [2]:
from selenium import webdriver
import time

from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait

from selenium.webdriver.support import expected_conditions as ec

from selenium.webdriver.chrome.options import Options

from bs4 import BeautifulSoup

import re

import numpy as np
import pandas as pd

In [3]:
path = r"C:\chromedriver.exe"

In [4]:
chrome_option = Options()
# 필요한 크롬 브라우저에 대한 옵션들을 추가한다. 

chrome_option.add_argument("--headless")
# 크롬 브라우저 직접 제어할 때 앞에서 지정한 옵션 사용

driver = webdriver.Chrome(path, options = chrome_option)

In [ ]:
del data

### 처음에 크롤링한건 6월,
### 이후에 1-5월 모두 크롤링하고, 작년도 1-5월과 작년도 6-9월까지 같은 코드로 크롤링

# May

In [4]:
data_may = pd.DataFrame() # dataframe 이름 바꾸기

In [5]:
data_may = data_may.append({    # dataframe 이름 바꾸기
    "위치(도)" : "",
    "위치(시군구)": "",
    "품종" : ""
}, ignore_index = True)

In [6]:
data_may # dataframe 이름 바꾸기

  위치(도) 위치(시군구) 품종
0

In [ ]:
# 옵션 지정 없이, 브라우저 창 같이 보면서 하려고..
driver = webdriver.Chrome(path)
# 처음에 브라우저 로딩 등 기다림을 위해서 대기..
driver.implicitly_wait(5)
# 화면 크기
driver.maximize_window()

In [7]:
try:
    
    for j in range(1, 150):
        url1 = "https://www.animal.go.kr/front/awtis/protection/protectionList.do?totalCount=4185&pageSize=10&boardId=&desertionNo=&menuNo=1000000060&searchSDate=2021-05-05&searchEDate=2021-06-04&searchUprCd=&searchOrgCd=&searchCareRegNo=&searchUpKindCd=417000&searchKindCd=&&page="
        url = url1+str(j)
        driver.get(url) 

        for x in range(1, 10):
            dog_xpath = f'//*[@id="searchList"]/div[4]/ul[2]/li[{x}]/div[1]/a'
            driver.find_element_by_xpath(dog_xpath).click()

            a = driver.page_source
            soup=BeautifulSoup(a, "html.parser")


            species = soup.find("table").find_all("td", class_ = "last")[1].get_text().split("]")[1].strip() # 품종
            location_1 = soup.find("table").find_all("td", class_ = "last")[0].get_text().split("-")[0] #위치 '도' 기준
            location_2 = soup.find("table").find_all("td", class_ = "last")[0].get_text().split("-")[1] # 위치 '시군구' 기준

            data_may.at[(j*10)+(x-1)-10, "품종"] = species
            data_may.at[(j*10)+(x-1)-10, "위치(도)"] = location_1
            data_may.at[(j*10)+(x-1)-10, "위치(시군구)"] = location_2  





            back_path = '//*[@id="sub_con"]/div[2]/a/img'
            driver.find_element_by_xpath(back_path).click() # 목록으로 돌아가기
            
except Exception : 
    pass

In [8]:
data_may

     위치(도) 위치(시군구)   품종
0       강원      삼척  믹스견
1       전남      영광  믹스견
2       전남      영광  믹스견
3       전남      영광  믹스견
4       전남      영광  믹스견
...    ...     ...  ...
1484    강원      동해  믹스견
1485    강원      동해  믹스견
1486    경기      양평  믹스견
1487    경기      양평  믹스견
1488    경기      양평  믹스견

[1341 rows x 3 columns]

In [39]:
pd.DataFrame(data_may).to_excel('./MAY.xlsx', index = False)

In [ ]:
https://www.animal.go.kr/front/awtis/protection/protectionList.do?totalCount=4185&pageSize=10&boardId=&desertionNo=&menuNo=1000000060&searchSDate=2021-01-05&searchEDate=2021-02-04&searchUprCd=&searchOrgCd=&searchCareRegNo=&searchUpKindCd=417000&searchKindCd=&&page=

In [ ]:
6-5 ~ 7-5
5-5 ~ 6-4 
4-5 ~ 5-4

# April

In [9]:
data_april = pd.DataFrame() # dataframe 이름 바꾸기

data_april = data_april.append({    # dataframe 이름 바꾸기
    "위치(도)" : "",
    "위치(시군구)": "",
    "품종" : ""
}, ignore_index = True)

data_april # dataframe 이름 바꾸기

  위치(도) 위치(시군구) 품종
0

In [10]:
# 옵션 지정 없이, 브라우저 창 같이 보면서 하려고..
driver = webdriver.Chrome(path)
# 처음에 브라우저 로딩 등 기다림을 위해서 대기..
driver.implicitly_wait(5)
# 화면 크기
driver.maximize_window()

In [11]:
try:
    
    for j in range(1, 150):
        url1 = "https://www.animal.go.kr/front/awtis/protection/protectionList.do?totalCount=4185&pageSize=10&boardId=&desertionNo=&menuNo=1000000060&searchSDate=2021-04-05&searchEDate=2021-05-04&searchUprCd=&searchOrgCd=&searchCareRegNo=&searchUpKindCd=417000&searchKindCd=&&page="
        url = url1+str(j)
        driver.get(url) 

        for x in range(1, 10):
            dog_xpath = f'//*[@id="searchList"]/div[4]/ul[2]/li[{x}]/div[1]/a'
            driver.find_element_by_xpath(dog_xpath).click()

            a = driver.page_source
            soup=BeautifulSoup(a, "html.parser")


            species = soup.find("table").find_all("td", class_ = "last")[1].get_text().split("]")[1].strip() # 품종
            location_1 = soup.find("table").find_all("td", class_ = "last")[0].get_text().split("-")[0] #위치 '도' 기준
            location_2 = soup.find("table").find_all("td", class_ = "last")[0].get_text().split("-")[1] # 위치 '시군구' 기준

            data_april.at[(j*10)+(x-1)-10, "품종"] = species
            data_april.at[(j*10)+(x-1)-10, "위치(도)"] = location_1
            data_april.at[(j*10)+(x-1)-10, "위치(시군구)"] = location_2  





            back_path = '//*[@id="sub_con"]/div[2]/a/img'
            driver.find_element_by_xpath(back_path).click() # 목록으로 돌아가기
            
except Exception : 
    pass

In [16]:
data_april

    위치(도) 위치(시군구)   품종
0      경기      안성  믹스견
1      경기      안성  믹스견
2      경남      산청  믹스견
3      경남      산청  믹스견
4      부산      사하  믹스견
..    ...     ...  ...
921    충북      충주  믹스견
922    강원      동해  믹스견
923    경기      의왕  믹스견
924    광주      광산  믹스견
925    광주      서구  믹스견

[834 rows x 3 columns]

In [40]:
pd.DataFrame(data_april).to_excel('./APRIL.xlsx', index = False)

# March

In [15]:
data_march = pd.DataFrame() # dataframe 이름 바꾸기

data_march = data_march.append({    # dataframe 이름 바꾸기
    "위치(도)" : "",
    "위치(시군구)": "",
    "품종" : ""
}, ignore_index = True)

data_march # dataframe 이름 바꾸기

  위치(도) 위치(시군구) 품종
0

In [18]:
data_march

  위치(도) 위치(시군구) 품종
0

In [19]:
# 옵션 지정 없이, 브라우저 창 같이 보면서 하려고..
driver = webdriver.Chrome(path)
# 처음에 브라우저 로딩 등 기다림을 위해서 대기..
driver.implicitly_wait(5)
# 화면 크기
driver.maximize_window()

In [20]:
try:
    
    for j in range(1, 87):
        url1 = "https://www.animal.go.kr/front/awtis/protection/protectionList.do?totalCount=4185&pageSize=10&boardId=&desertionNo=&menuNo=1000000060&searchSDate=2021-03-05&searchEDate=2021-04-04&searchUprCd=&searchOrgCd=&searchCareRegNo=&searchUpKindCd=417000&searchKindCd=&&page="
        url = url1+str(j)
        driver.get(url) 

        for x in range(1, 10):
            dog_xpath = f'//*[@id="searchList"]/div[4]/ul[2]/li[{x}]/div[1]/a'
            driver.find_element_by_xpath(dog_xpath).click()

            a = driver.page_source
            soup=BeautifulSoup(a, "html.parser")


            species = soup.find("table").find_all("td", class_ = "last")[1].get_text().split("]")[1].strip() # 품종
            location_1 = soup.find("table").find_all("td", class_ = "last")[0].get_text().split("-")[0] #위치 '도' 기준
            location_2 = soup.find("table").find_all("td", class_ = "last")[0].get_text().split("-")[1] # 위치 '시군구' 기준

            data_march.at[(j*10)+(x-1)-10, "품종"] = species
            data_march.at[(j*10)+(x-1)-10, "위치(도)"] = location_1
            data_march.at[(j*10)+(x-1)-10, "위치(시군구)"] = location_2  





            back_path = '//*[@id="sub_con"]/div[2]/a/img'
            driver.find_element_by_xpath(back_path).click() # 목록으로 돌아가기
            
except Exception : 
    pass

In [21]:
data_march

    위치(도) 위치(시군구)   품종
0      대전      중구  믹스견
1      대전      중구  믹스견
2      경북      김천  믹스견
3      경북      김천  믹스견
4      전남      신안  믹스견
..    ...     ...  ...
854    강원      원주  믹스견
855    강원      원주  믹스견
856    강원      원주  믹스견
857    강원      원주  믹스견
858    강원      원주  믹스견

[774 rows x 3 columns]

In [41]:
pd.DataFrame(data_march).to_excel('./MARCH.xlsx', index = False)

# FEB

In [22]:
data_feb = pd.DataFrame() # dataframe 이름 바꾸기

data_feb = data_feb.append({    # dataframe 이름 바꾸기
    "위치(도)" : "",
    "위치(시군구)": "",
    "품종" : ""
}, ignore_index = True)

data_feb # dataframe 이름 바꾸기

  위치(도) 위치(시군구) 품종
0

In [23]:
# 옵션 지정 없이, 브라우저 창 같이 보면서 하려고..
driver = webdriver.Chrome(path)
# 처음에 브라우저 로딩 등 기다림을 위해서 대기..
driver.implicitly_wait(5)
# 화면 크기
driver.maximize_window()

In [24]:
try:
    
    for j in range(1, 56):
        url1 = "https://www.animal.go.kr/front/awtis/protection/protectionList.do?totalCount=4185&pageSize=10&boardId=&desertionNo=&menuNo=1000000060&searchSDate=2021-02-05&searchEDate=2021-03-04&searchUprCd=&searchOrgCd=&searchCareRegNo=&searchUpKindCd=417000&searchKindCd=&&page="
        url = url1+str(j)
        driver.get(url) 

        for x in range(1, 10):
            dog_xpath = f'//*[@id="searchList"]/div[4]/ul[2]/li[{x}]/div[1]/a'
            driver.find_element_by_xpath(dog_xpath).click()

            a = driver.page_source
            soup=BeautifulSoup(a, "html.parser")


            species = soup.find("table").find_all("td", class_ = "last")[1].get_text().split("]")[1].strip() # 품종
            location_1 = soup.find("table").find_all("td", class_ = "last")[0].get_text().split("-")[0] #위치 '도' 기준
            location_2 = soup.find("table").find_all("td", class_ = "last")[0].get_text().split("-")[1] # 위치 '시군구' 기준

            data_feb.at[(j*10)+(x-1)-10, "품종"] = species
            data_feb.at[(j*10)+(x-1)-10, "위치(도)"] = location_1
            data_feb.at[(j*10)+(x-1)-10, "위치(시군구)"] = location_2  





            back_path = '//*[@id="sub_con"]/div[2]/a/img'
            driver.find_element_by_xpath(back_path).click() # 목록으로 돌아가기
            
except Exception : 
    pass

In [25]:
data_feb

    위치(도) 위치(시군구)   품종
0      대전      유성  진도견
1      경남      고성  믹스견
2      경남      고성  믹스견
3      경남      고성  믹스견
4      경북      영양  진도견
..    ...     ...  ...
544    전북      전주  믹스견
545    전북      전주  믹스견
546    전북      전주  믹스견
547    전북      전주  믹스견
548    전북      전주  믹스견

[495 rows x 3 columns]

In [42]:
pd.DataFrame(data_feb).to_excel('./FEB.xlsx', index = False)

# JAN

In [35]:
data_jan = pd.DataFrame() # dataframe 이름 바꾸기

data_jan = data_jan.append({    # dataframe 이름 바꾸기
    "위치(도)" : "",
    "위치(시군구)": "",
    "품종" : ""
}, ignore_index = True)

data_jan # dataframe 이름 바꾸기

  위치(도) 위치(시군구) 품종
0

In [36]:
# 옵션 지정 없이, 브라우저 창 같이 보면서 하려고..
driver = webdriver.Chrome(path)
# 처음에 브라우저 로딩 등 기다림을 위해서 대기..
driver.implicitly_wait(5)
# 화면 크기
driver.maximize_window()

In [37]:
try:
    
    for j in range(1, 66):
        url1 = "https://www.animal.go.kr/front/awtis/protection/protectionList.do?totalCount=4185&pageSize=10&boardId=&desertionNo=&menuNo=1000000060&searchSDate=2021-01-05&searchEDate=2021-02-04&searchUprCd=&searchOrgCd=&searchCareRegNo=&searchUpKindCd=417000&searchKindCd=&&page="
        url = url1+str(j)
        driver.get(url) 

        for x in range(1, 10):
            dog_xpath = f'//*[@id="searchList"]/div[4]/ul[2]/li[{x}]/div[1]/a'
            driver.find_element_by_xpath(dog_xpath).click()

            a = driver.page_source
            soup=BeautifulSoup(a, "html.parser")


            species = soup.find("table").find_all("td", class_ = "last")[1].get_text().split("]")[1].strip() # 품종
            location_1 = soup.find("table").find_all("td", class_ = "last")[0].get_text().split("-")[0] #위치 '도' 기준
            location_2 = soup.find("table").find_all("td", class_ = "last")[0].get_text().split("-")[1] # 위치 '시군구' 기준

            data_jan.at[(j*10)+(x-1)-10, "품종"] = species
            data_jan.at[(j*10)+(x-1)-10, "위치(도)"] = location_1
            data_jan.at[(j*10)+(x-1)-10, "위치(시군구)"] = location_2  





            back_path = '//*[@id="sub_con"]/div[2]/a/img'
            driver.find_element_by_xpath(back_path).click() # 목록으로 돌아가기
            
except Exception : 
    pass

In [47]:
data_jan['월'] = 1

In [43]:
pd.DataFrame(data_jan).to_excel('./JAN_1.xlsx', index = False)

In [53]:
data_feb['월'] = 2

In [55]:
data_march['월'] = 3

In [57]:
data_april['월'] = 4

In [58]:
data_may['월'] = 5

In [59]:
pd.DataFrame(data_jan).to_excel('./JAN_1.xlsx', index = False)
pd.DataFrame(data_feb).to_excel('./FEB_1.xlsx', index = False)
pd.DataFrame(data_march).to_excel('./MAR_1.xlsx', index = False)
pd.DataFrame(data_april).to_excel('./APR_1.xlsx', index = False)
pd.DataFrame(data_may).to_excel('./MAY_1.xlsx', index = False)

In [65]:
combined = pd.concat([data_jan, data_feb], axis=0, ignore_index = True)

In [67]:
combined = pd.concat([combined, data_march], axis=0, ignore_index = True)

In [69]:
combined = pd.concat([combined, data_april], axis=0, ignore_index = True)

In [71]:
combined = pd.concat([combined, data_may], axis=0, ignore_index = True)

In [73]:
pd.DataFrame(combined).to_excel('./COMBINED.xlsx', index = False)

In [ ]:
https://www.animal.go.kr/front/awtis/protection/protectionList.do?totalCount=4185&pageSize=10&boardId=&desertionNo=&menuNo=1000000060&searchSDate=2021-01-05&searchEDate=2021-07-05&searchUprCd=&searchOrgCd=&searchCareRegNo=&searchUpKindCd=417000&searchKindCd=&&page=1

# 1-5월 시도, 시군구, 품종

In [72]:
combined

     위치(도) 위치(시군구)   품종  월
0       전남      장성  믹스견  1
1       전남      장성  믹스견  1
2       전남      장성  믹스견  1
3       전남      장성  믹스견  1
4       전남      장성  믹스견  1
...    ...     ...  ... ..
4024    강원      동해  믹스견  5
4025    강원      동해  믹스견  5
4026    경기      양평  믹스견  5
4027    경기      양평  믹스견  5
4028    경기      양평  믹스견  5

[4029 rows x 4 columns]

In [18]:
data_all = pd.DataFrame() # dataframe 이름 바꾸기

data_all = data_all.append({    # dataframe 이름 바꾸기
    "위치(도)" : "",
    "위치(시군구)": "",
    "품종" : "",
    "특징" : ""
}, ignore_index = True)

 # dataframe 이름 바꾸기

In [19]:
data_all

  위치(도) 위치(시군구) 특징 품종
0

In [8]:
words = [
    '슬개골', '쓸개골', '병', '부정교합', '피부병', '부상', '이상', '진드기', '옴', '탈모', '심장사상충', '사상충', '양성', '파보',
    '코로나', '파행', '고름', '휘어', '휨', '휘었', '피부명','녹내장', '시력', '경련', '발작',
    '장애', '상처', '눈곱', '눈꼽', '결막염', '질환', '외이염', '귓병', '귀병', '감염', '나이많음', '늙', '골절', '병변', '안구',  
    '백내장', '치석', '부정', '구더기', '짓무름', '다쳐', '다침', '마비', '통증', '출혈', '임신', '유선', '유즙', '탈구', '탈골',  
    '종양', '탈장', '비만', '기관지염', '뇌경색', '뇌증', '뇌졸증', '신경', '증상', '손상', '염증', '흉터', '오염', '허약', '탈진',
    '광견병', '돌출', '교통사고', '다침', '다쳤', '절음', '적출', '수술', '사고', '전지', '후지', '파행'
    '경계', '경계심', '입질', '예민', '야생', '예민함', '예민', '공격성', '사나움', '사납', '짖음', '하울링', '늑대소리', '울어', 
    '소리지름', '낑낑', '소심', '으르렁', '짖', '공포', '피함', '사나운', '사나', '더러움', '더럽', '공격적', '따르지' 
]


filters = ["음성", "공격적이지", "없음", "접종", "사납지"]

In [9]:
# 옵션 지정 없이, 브라우저 창 같이 보면서 하려고..
driver = webdriver.Chrome(path)
# 처음에 브라우저 로딩 등 기다림을 위해서 대기..
driver.implicitly_wait(5)
# 화면 크기
driver.maximize_window()

In [20]:
try:
    
    for j in range(1, 761):
        url1 = "https://www.animal.go.kr/front/awtis/protection/protectionList.do?totalCount=4185&pageSize=10&boardId=&desertionNo=&menuNo=1000000060&searchSDate=2021-01-05&searchEDate=2021-07-05&searchUprCd=&searchOrgCd=&searchCareRegNo=&searchUpKindCd=417000&searchKindCd=&&page=1"
        url = url1+str(j)
        driver.get(url) 

        for x in range(1, 10):
            dog_xpath = f'//*[@id="searchList"]/div[4]/ul[2]/li[{x}]/div[1]/a'
            driver.find_element_by_xpath(dog_xpath).click()

            a = driver.page_source
            soup=BeautifulSoup(a, "html.parser")


            species = soup.find("table").find_all("td", class_ = "last")[1].get_text().split("]")[1].strip() # 품종
            location_1 = soup.find("table").find_all("td", class_ = "last")[0].get_text().split("-")[0] #위치 '도' 기준
            location_2 = soup.find("table").find_all("td", class_ = "last")[0].get_text().split("-")[1] # 위치 '시군구' 기준
            charac = soup.find("table").find_all("td", class_="last")[7].get_text() #특징

            data_all.at[(j*10)+(x-1)-10, "품종"] = species
            data_all.at[(j*10)+(x-1)-10, "위치(도)"] = location_1
            data_all.at[(j*10)+(x-1)-10, "위치(시군구)"] = location_2  
            for k in words:
                match = re.search(k, charac) 
                if match :
                    print(charac)
                    data_all.at[(j*10)+(x-1)-10, "특징"] = charac 
                elif match == -1 : 
                    data_all.at[(j*10)+(x-1)-10, "특징"] = "0"





            back_path = '//*[@id="sub_con"]/div[2]/a/img'
            driver.find_element_by_xpath(back_path).click() # 목록으로 돌아가기
            
except Exception : 
    pass

양귀쫑긋. 코주황+검정. 입질/으르렁거림. 꼬리단미안됨. 털때탐.
양귀쫑긋. 코주황+검정. 입질/으르렁거림. 꼬리단미안됨. 털때탐.
양귀쫑긋. 콧등상처. 코갈색. 사나움. 입질. 꼬리단미안됨. 털때탐.
양귀쫑긋. 콧등상처. 코갈색. 사나움. 입질. 꼬리단미안됨. 털때탐.
양귀쫑긋. 콧등상처. 코갈색. 사나움. 입질. 꼬리단미안됨. 털때탐.
양귀쫑긋. 콧등상처. 코갈색. 사나움. 입질. 꼬리단미안됨. 털때탐.
양귀쫑긋. 코갈+검. 사나움/입질/칩유무확인불가. 꼬리단미안됨. 털때탐.
양귀쫑긋. 코갈+검. 사나움/입질/칩유무확인불가. 꼬리단미안됨. 털때탐.
양귀쫑긋. 코갈+검. 사나움/입질/칩유무확인불가. 꼬리단미안됨. 털때탐.
양눈눈물자국심함. 양눈백내장. 온순함. 얌전함. 꼬리단미안됨. 털때탐.
초록바탕+노란테두리 목줄. 활발/사람따름. 꼬리단미안됨. 털때탐. 양슬개골심함.
파란바탕+빨간테두리 목줄. 유선처짐. 겁있음/입질있음. 꼬리단미안됨. 털때탐.
파란바탕+빨간테두리 목줄. 유선처짐. 겁있음/입질있음. 꼬리단미안됨. 털때탐.
양귀처짐. 공격적/경계심함. 꼬리단미안됨. 털때탐.
양귀처짐. 공격적/경계심함. 꼬리단미안됨. 털때탐.
양귀쫑긋. 코검정. 겁/소심/방어적입질. 꼬리단미안됨. 털상태 양호.
양귀쫑긋. 코검정. 겁/소심/방어적입질. 꼬리단미안됨. 털상태 양호.
양귀쫑긋. 코갈색. 입질/겁/사나움. 꼬리단미안됨. 털때탐.
양귀쫑긋. 코갈색. 입질/겁/사나움. 꼬리단미안됨. 털때탐.
양귀쫑긋. 코갈색. 입질/겁/사나움. 꼬리단미안됨. 털때탐.
양귀처짐. 코갈색. 겁/입질. 꼬리단미안됨. 털때탐.
양귀반접힘. 코검정. 소심/겁/입질. 꼬리단미안됨. 털때탐.
양귀반접힘. 코검정. 소심/겁/입질. 꼬리단미안됨. 털때탐.
양귀쫑긋. 코검정. 겁/소심/방어적입질. 꼬리단미안됨. 털때탐.
양귀쫑긋. 코검정. 겁/소심/방어적입질. 꼬리단미안됨. 털때탐.
양귀끝 처짐. 코검정. 겁많음/입질. 꼬리단미안됨. 털때탐.
양귀쫑긋. 코갈+검. 겁있음/소심/사람따름. 꼬리단미안됨. 털때탐.
양귀쫑긋. 코갈+검. 겁있음/소심/사람따름. 꼬리단미안됨. 털때탐.
양귀쫑긋. 코갈+검. 겁있음/소심/사람따름. 꼬리단미안됨. 털때탐.
양귀쫑긋. 코갈+검. 겁있음/소심/사람따름. 꼬리단미안됨. 털때탐.
오른쪽 앞다리 다침
오른쪽 앞다리 다침
몸곳곳상처있음. 겁많음. 경계함. 털때탐.
도로에서 발견/ 아직은..소심한 성격
 온순하고 조용함, 부정교합, 하트모양 코가 매력포인트
 온순하고 조용함, 부정교합, 하트모양 코가 매력포인트
발견당시 냄새가 심하고 진드기가 있어 발견자가 미용함
인근 가정집에 들어와서 포획하여 구조, 새끼와 함께 구조, 입질 있음
6개월추정,사람잘따르고애교많음,큰눈,코주위점 황흑색의 무늬가 예쁘게 들어감(실물이더예쁨),피부병의심
6개월추정,사람잘따르고애교많음,큰눈,코주위점 황흑색의 무늬가 예쁘게 들어감(실물이더예쁨),피부병의심
순함, 피부병 있어보임
순함, 피부병 있어보임
하얀색 사납지 않음
중성화 수술 되어있고, 사람품을 너무 좋아함.
구조시 약간의 경계심이 있었으나, 사람 잘 따르고 온순함 ( 배가 엄청 고팠는지 밥을 허겁지겁 먹음)
피부질환
피부질환
입질있음
입질이 심해 마취 후 포획
고령.백내장.오른송곳니없음.입주변/꼬리끝/발끝변색.사람따름.구강질환/치석.유선종양.피부질환.
고령.백내장.오른송곳니없음.입주변/꼬리끝/발끝변색.사람따름.구강질환/치석.유선종양.피부질환.
고령.백내장.오른송곳니없음.입주변/꼬리끝/발끝변색.사람따름.구강질환/치석.유선종양.피부질환.
고령.백내장.오른송곳니없음.입주변/꼬리끝/발끝변색.사람따름.구강질환/치석.유선종양.피부질환.
고령.백내장.오른송곳니없음.입주변/꼬리끝/발끝변색.사람따름.구강질환/치석.유선종양.피부질환.
(개체관리번호2252)생후7개월, 경계심
(개체관리번호2250)경계심
(개체관리번호2246)생후8개월, 경계심
화이트컬러에 야생화가많이되어있어 경계심이강함
화이트컬러에 야생화가많이되어있어 경계심이강함
좌측 전지 부정유합 상태, 나무에 묶여 있는 상태로 구조
좌측 전지 부정유합 상태, 나무에 묶여 있는 상태로 구조
4개월령, 종합백신접종,코로나장염접종,광견병접종,레볼루션.
4개월령, 종합백신접종,코로나장염접종,광견병접종,레볼루션.
4개월령, 종합백신접종,코로나장염접종,광견병접종,레볼루션.
털이길고 사나운편임
털이길고 사나운편임
순함, 피부 안 좋음, 파보 코로나 음성
순함, 피부 안 좋음, 파보 코로나 음성
사상충 음성, 순함, 사람 잘 따름
파랑 빨강 목줄 착용, 사상충 양성, 순함
파랑 빨강 목줄 착용, 사상충 양성, 순함
1041호(관리) 574호(공고) 경계심 있음.
겁이 많음, 식욕없음, 유기견생활 오래한 듯 보임,진드기 많음, 사상충감염의심
겁이 많음, 식욕없음, 유기견생활 오래한 듯 보임,진드기 많음, 사상충감염의심
겁이 많음, 식욕없음, 유기견생활 오래한 듯 보임,진드기 많음, 사상충감염의심
양귀쫑긋. 눈곱약간. 코검정. 진드기오염. 겁있음/사람좋아함/활발함. 꼬리단미안됨. 털상태불량.
양귀쫑긋. 눈곱약간. 코검정. 진드기오염. 겁있음/사람좋아함/활발함. 꼬리단미안됨. 털상태불량.
양귀쫑긋. 눈곱약간. 코검정. 진드기오염. 겁있음/사람좋아함/활발함. 꼬리단미안됨. 털상태불량.
양귀접힘. 코검정. 겁있음/경계함/만지면놀람/소심. 꼬리단미안됨. 털상태양호.
양귀쫑긋. 귀장식털. 코검정. 입질/겁많음/경계함. 단미안됨. 털상태양호.
파란바탕+노란줄무늬목줄.코검정.진드기오염심함.사람따름/활발.단미안됨.털상태불량.
파란바탕+노란줄무늬목줄.코검정.진드기오염심함.사람따름/활발.단미안됨.털상태불량.
양귀반접힘. 코검정. 사람따름/낑낑댐. 꼬리단미안됨. 털상태양호.
양귀반접힘. 코검정. 사람따름/낑낑댐. 꼬리단미안됨. 털상태 양호.
양귀반접힘. 코갈색. 유선발달. 사람따름/온순. 꼬리단미안됨. 털때탐.
양귀반접힘. 코검정. 진드기오염매우심함. 겁있음/소심. 꼬리단미안됨. 털때탐.
양귀반접힘. 코검정. 진드기오염매우심함. 겁있음/소심. 꼬리단미안됨. 털때탐.
양귀반접힘. 코검정. 진드기오염매우심함. 겁있음/소심. 꼬리단미안됨. 털때탐.
붉은목걸이/사슬/성조기무늬 리드줄. 양귀쫑긋. 코갈색. 겁있음/건들면 방어적입질.
낡은붉은목걸이/사슬리드줄.양귀반접힘.코검정.매우사나움/짖음/칩유무확인불가.
낡은붉은목걸이/사슬리드줄.양귀반접힘.코검정.매우사나움/짖음/칩유무확인불가.
낡은붉은목걸이/사슬리드줄.양귀반접힘.코검정.매우사나움/짖음/칩유무확인불가.
낡은붉은목걸이/사슬리드줄.양귀반접힘.코검정.매우사나움/짖음/칩유무확인불가.
겁이 많음/누런눈꼽 약간 있음
뒷다리다침,입질이심함,강서구1-229호
뒷다리다침,입질이심함,강서구1-229호
뒷다리다침,입질이심함,강서구1-229호
양귀쫑긋/귀 뒤로 잘넘김. 코갈색. 겁많음/소심/사람따름.
양귀쫑긋. 코검정. 겁있음/소심/사람따름. 꼬리단미안됨. 털때탐.
양귀쫑긋. 코검정. 진드기오염. 피부질환. 소심/겁있음. 꼬리단미안됨. 털때탐.
양귀쫑긋. 코검정. 진드기오염. 피부질환. 소심/겁있음. 꼬리단미안됨. 털때탐.
양귀쫑긋. 코검정. 진드기오염. 피부질환. 소심/겁있음. 꼬리단미안됨. 털때탐.
양귀쫑긋. 코검정. 진드기오염. 피부질환. 소심/겁있음. 꼬리단미안됨. 털때탐.
양귀쫑긋/코갈색. 전신 진드기오염. 겁있음. 털때탐. 꼬리단미안됨.
양귀쫑긋/코갈색. 전신 진드기오염. 겁있음. 털때탐. 꼬리단미안됨.
얌전하며, 경계심이 없음
순함,경계심 있음
순하면서 경계심 심함
환하게웃는미소가절로웃음을자아넴경계심X입질X제보자분께서많은도움을주심
환하게웃는미소가절로웃음을자아넴경계심X입질X제보자분께서많은도움을주심
출산한지 얼마 안되어보임, 새끼들은 없음, 진드기 많음, 엄청 소심하고 눈치 많이 봄, 만질수는 있음
출산한지 얼마 안되어보임, 새끼들은 없음, 진드기 많음, 엄청 소심하고 눈치 많이 봄, 만질수는 있음
목을 묶는 끈이 매달려 있음, 유실견으로 추정됨, 치석증심함, 진드기부착, 사상충 의심됨
목을 묶는 끈이 매달려 있음, 유실견으로 추정됨, 치석증심함, 진드기부착, 사상충 의심됨
목을 묶는 끈이 매달려 있음, 유실견으로 추정됨, 치석증심함, 진드기부착, 사상충 의심됨
파란색 목줄 착용, 순함, 양쪽 이빨 많이 없음, 진드기약 처치
귀부분이 다른곳에비해 짙은갈색이고 살짝 접혀있다, 사납지 않으나 겁이 많아 낯가림이 심하다
순함,왼쪽눈 백내장 및 안질환
순함,왼쪽눈 백내장 및 안질환
피부병 심함
피부병 심함
피부병
피부병
치석심하며미용한지두달이상되엉보이고온순하나약간경계심있고조용함
치석심하며미용한지두달이상되엉보이고온순하나약간경계심있고조용함
치석심하며미용한지두달이상되엉보이고온순하나약간경계심있고조용함
양귀쫑긋. 왼귓바퀴 일부 찢긴흔적. 코검정. 소심함/겁있음/가만히 있으면 조금씩 다가옴.
양귀쫑긋. 왼귓바퀴 일부 찢긴흔적. 코검정. 소심함/겁있음/가만히 있으면 조금씩 다가옴.
교통사고 왼쪽 골반 골절,순함, 사상충 음성
교통사고 왼쪽 골반 골절,순함, 사상충 음성
교통사고 왼쪽 골반 골절,순함, 사상충 음성
교통사고 왼쪽 골반 골절,순함, 사상충 음성
진드기많음
경계심함
구조당시 오른쪽눈부위가다쳐있고 영양실조상태로구조
진드기
검은색 목걸이/ 소심함
순함,빨강 파랑 목줄 착용, 사상충 음성, 진드기약 처방
순함,빨강 파랑 목줄 착용, 사상충 음성, 진드기약 처방
사나움, 주변닭농가 닭물어죽임 (들개화)
사나움, 주변닭농가 닭물어죽임 (들개화)
매우짖음 심함
매우짖음 심함
양귀접힘. 코검정. 진드기오염. 사람좋아함. 꼬리단미안됨. 털상태 양호.
양귀접힘. 코검정. 진드기오염. 사람좋아함. 꼬리단미안됨. 털상태 양호.
양귀앞으로 반 접힘. 코검정. 겁있음/소심. 꼬리단미안됨. 털상태 양호.
양귀접힘. 코검정. 겁많음. 입질. 경계함. 꼬리단미안됨.
양귀접힘. 코갈색. 으르렁거림. 겁있음. 소심함. 꼬리단미안됨.
양귀접힘. 코갈색. 으르렁거림. 겁있음. 소심함. 꼬리단미안됨.
눈아래부위에서콧등까지피부질환탈모.우측눈아래피부파임/출혈.설사.경계함.겁많음.파보/코로나검사:음성
눈아래부위에서콧등까지피부질환탈모.우측눈아래피부파임/출혈.설사.경계함.겁많음.파보/코로나검사:음성
눈아래부위에서콧등까지피부질환탈모.우측눈아래피부파임/출혈.설사.경계함.겁많음.파보/코로나검사:음성
눈아래부위에서콧등까지피부질환탈모.우측눈아래피부파임/출혈.설사.경계함.겁많음.파보/코로나검사:음성
눈아래부위에서콧등까지피부질환탈모.우측눈아래피부파임/출혈.설사.경계함.겁많음.파보/코로나검사:음성
부상견, 적색목줄착용
사나움
사나움
양귀접힘. 코검정. 사람따름/온순. 진드기오염.
양귀접힘. 코검정. 사람따름/온순. 진드기오염.
5개월령이고 피부병 심함
5개월령이고 피부병 심함
진드기가 좀 있고, 심하지는 않지만 등에 상처가 있음
진드기가 좀 있고, 심하지는 않지만 등에 상처가 있음
21-0645 비비, 다리부상
왼앞다리붕대하고옴. 좌 전지 요/척골절. 코검정. 사람좋아함. 활발함. 털때탐.
왼앞다리붕대하고옴. 좌 전지 요/척골절. 코검정. 사람좋아함. 활발함. 털때탐.
왼앞다리붕대하고옴. 좌 전지 요/척골절. 코검정. 사람좋아함. 활발함. 털때탐.
(개체관리번호2235)우안구기형
(개체관리번호2234)생후11개월, 목피부병, 경계심
(개체관리번호2234)생후11개월, 목피부병, 경계심
(개체관리번호2234)생후11개월, 목피부병, 경계심
경계심 심함
개에 공격성 큼, 사나움
개에 공격성 큼, 사나움
개에 공격성 큼, 사나움
임신 추정
진도믹스 추정. 겁이 많고 사나움
진도믹스 추정. 겁이 많고 사나움
진도믹스 추정. 겁이많고 사나움
진도믹스 추정. 겁이많고 사나움
순함/임신추정/설사있음
피부병, 허약, 탈진, 핑크칼라옷착용
피부병, 허약, 탈진, 핑크칼라옷착용
피부병, 허약, 탈진, 핑크칼라옷착용
피부병, 허약, 탈진, 핑크칼라옷착용
양귀쫑긋. 코검정. 칩유무확인불가. 겁많음. 으르렁거림. 도망다님. 꼬리단미안됨.
양귀반접힘. 코검정. 유선늘어짐/유두큼. 다리짧음. 겁약간. 사람따름. 얌전함. 꼬리단미안됨.
양귀반접힘. 코검정. 진드기오염. 다리짧음. 사람따름. 활발함. 꼬리단미안됨.
양귀반접힘. 코검정. 진드기오염. 다리짧음. 사람따름. 활발함. 꼬리단미안됨.
양귀반접힘. 코검정. 겁많음. 도망다님. 소심함. 칩유무확인불가.
양귀반접힘. 코검정. 진드기오염. 겁있음. 입질. 경계함. 꼬리단미안됨. 털때탐.
양귀반접힘. 코검정. 진드기오염. 겁있음. 입질. 경계함. 꼬리단미안됨. 털때탐.
양귀반접힘. 코검정. 진드기오염. 겁있음. 입질. 경계함. 꼬리단미안됨. 털때탐.
양귀쫑긋. 코검정+갈색. 으르렁거림. 겁많음. 짖음. 칩유무확인불가. 꼬리단미안됨.
양귀쫑긋. 코검정+갈색. 으르렁거림. 겁많음. 짖음. 칩유무확인불가. 꼬리단미안됨.
양귀쫑긋. 코검정+갈색. 으르렁거림. 겁많음. 짖음. 칩유무확인불가. 꼬리단미안됨.
심장사상충 음성, 길거리 배회
심장사상충 음성, 길거리 배회
폐공장에서 5마리 함께 구조/ 피부병 심함
폐공장에서 5마리 함께 구조/ 피부병 심함
폐공장에서 5마리 함께 구조/ 피부병 심함
폐공장에서 5마리 함께 구조/ 피부병 심함
폐공장에서 5마리 함께 구조/ 피부병 심함
폐공장에서 5마리 함께 구조/ 피부병 심함
폐공장에서 5마리 함께 구조/ 피부병 심함
폐공장에서 5마리 함께 구조/ 피부병 심함
봉암리차로에서교통사고 오른쪽뒷다리골절 목줄흔적으로 봉암리동네 개 인듯
봉암리차로에서교통사고 오른쪽뒷다리골절 목줄흔적으로 봉암리동네 개 인듯
봉암리차로에서교통사고 오른쪽뒷다리골절 목줄흔적으로 봉암리동네 개 인듯
진드기 감염이 심하며 현재 임신중
진드기 감염이 심하며 현재 임신중
진드기 감염이 심하며 현재 임신중
피부병 심하고 허약함
피부병 심하고 허약함
피부병 심하고 허약함
피부병 심하고 허약함
피부병 심하고 허약함
피부병 심하고 허약함
돌아다닌지꽤된듯함,진드기 큰거 많음,소심하고 겁많은 스타일,독특한 털색과 패턴
돌아다닌지꽤된듯함,진드기 큰거 많음,소심하고 겁많은 스타일,독특한 털색과 패턴
빨간색목테착용(집나온듯함,줄은없음),온순하고 사람잘따름,뒷다리쪽 약한상처있음
온순하고 소심한편
4개월,피부병,경계함
4개월,피부병,경계함
파보 코로나 음성, 구충제 사상충 진드기약 처방, 순함
파보 코로나 음성, 구충제 사상충 진드기약 처방, 순함
파보 코로나 음성, 구충제 사상충 진드기약 처방, 순함
파보 코로나 음성, 구충제 사상충 진드기약 처방, 순함
피부질환 있음
좌측안구 충혈 등쪽에 연한갈색 털 살짝 있음
약간은 소심하지만 긴 털이 매력적인 아이
눈병.
피부병,진드기,안질환,순함
피부병,진드기,안질환,순함
피부병,진드기,안질환,순함
피부병,진드기,안질환,순함
경도의 백내장
21-0639 하리, 좌측후지 대퇴골 골절, 목줄착용(파랑)
21-0639 하리, 좌측후지 대퇴골 골절, 목줄착용(파랑)
순함 , 사람좋아함, 윗입술 흉터
체격이 크고, 공격적임
야생화 됨
(개체관리번호2230)경계심, 심장사상충
(개체관리번호2230)경계심, 심장사상충
(개체관리번호2230)경계심, 심장사상충
(개체관리번호2227)경계심
(개체관리번호2226)경계심, 사상충
(개체관리번호2226)경계심, 사상충
(개체관리번호2212)경계심
겁많고 경계심함, 닭장습격
피부병심함.
피부병심함.
사람을 경계하고  좀 사나움
사람을 경계하고  좀 사나움
양귀반접힘. 코검정. 겁있음/소심/사람따름. 꼬리단미안됨. 털때탐.
양귀쫑긋. 코검정. 사람따름/활발함/낑낑댐. 꼬리단미안됨. 털때탐.
양귀접힘. 코검정. 진드기오염. 겁/소심/방어적입질/칩유무확인불가. 꼬리단미안됨. 털상태 양호.
양귀접힘. 코검정. 진드기오염. 겁/소심/방어적입질/칩유무확인불가. 꼬리단미안됨. 털상태 양호.
양귀접힘. 코검정. 진드기오염. 겁/소심/방어적입질/칩유무확인불가. 꼬리단미안됨. 털상태 양호.
양귀접힘. 코검정. 진드기오염. 겁/소심/방어적입질/칩유무확인불가. 꼬리단미안됨. 털상태 양호.
어미/새끼2 함께옴. 양귀접힘. 코검정. 사람따름/얌전함. 꼬리단미안됨. 털상태 양호.
어미/새끼2 함께옴. 양귀반접힘. 코검정. 겁있음/소심/만지면 놀람. 꼬리단미안됨. 털때탐.
어미/새끼2 함께옴. 양귀반접힘. 코검정. 겁있음/소심/만지면 놀람. 꼬리단미안됨. 털때탐.
코검정. 등쪽털엉킴. 사람따름. 꼬리단미안됨. 털때탐. 진드기오염. 양슬개골/우측심함. 돌변주의.
코검정. 등쪽털엉킴. 사람따름. 꼬리단미안됨. 털때탐. 진드기오염. 양슬개골/우측심함. 돌변주의.
코검정. 등쪽털엉킴. 사람따름. 꼬리단미안됨. 털때탐. 진드기오염. 양슬개골/우측심함. 돌변주의.
3개월추정 , 포획틀 , 마취포획 ,겁많음,예민함
3개월추정 , 포획틀 , 마취포획 ,겁많음,예민함
3개월추정 , 포획틀 , 마취포획 ,겁많음,예민함
흰색,이빨다남,허약,탈진 (3개월추정)
흰색,이빨다남,허약,탈진 (3개월추정)
검흰&이빨다남,허약,탈진(3개월추정)
검흰&이빨다남,허약,탈진(3개월추정)
구충제도포,1차접종(종합5,코로나),서구1-103호
구충제도포,1차접종(종합5,코로나),서구1-102호
구충제도포,1차접종(종합5,코로나),서구1-101호
구충제도포,1차접종(종합5,코로나),서구1-100호
공격성,탈진,피부질환,서구1-99호
공격성,탈진,피부질환,서구1-99호
공격성,탈진,피부질환,서구1-99호
공격성,탈진,피부질환,서구1-98호
공격성,탈진,피부질환,서구1-98호
공격성,탈진,피부질환,서구1-98호
공격성,피부질환,서구1-97호
공격성,피부질환,서구1-97호
심장사상충 양성
심장사상충 양성
심장사상충 양성
사람을 피함
파란목줄 착용, 약간 경계심 있음, 귀 끝 연갈색, 포획틀에 잡힘
생후 60일령 추정, 진드기 감염이 심하고 많이 마름
생후 60일령 추정, 진드기 감염이 심하고 많이 마름
소심함
예민함
예민함
예민함
예민. 소심
예민. 소심
예민. 소심
연갈,흰색, 온순, 진드기있음
눈안뜬 새끼강아지를 봐선 출산한지 얼마안되보임, 겁이많아 예민하다
눈안뜬 새끼강아지를 봐선 출산한지 얼마안되보임, 겁이많아 예민하다
소심함
소심함
소심하고 겁이많음
몸 곳곳에 상처. 진드기.
몸 곳곳에 상처. 진드기.
사나움
사나움
좌안 눈곱/눈물심함. 코갈색. 턱밑털오염/뭉침. 고령. 얌전/맘에안들면 입가씰룩거림.
좌안 눈곱/눈물심함. 코갈색. 턱밑털오염/뭉침. 고령. 얌전/맘에안들면 입가씰룩거림.
많이 짖음
많이 짖음
(개체관리번호2198)경계심
(개체관리번호2197)경계심
K-6-1-30 연갈색+흰색. 자견(10일령)5마리와 함께 들어옴. 예민함.
K-6-1-30 연갈색+흰색. 자견(10일령)5마리와 함께 들어옴. 예민함.
K-6-1-30 연갈색+흰색. 자견(10일령)5마리와 함께 들어옴. 예민함.
K-6-1-30 연갈색+흰색. 자견(10일령)5마리와 함께 들어옴. 예민함.
사람을 피함
체인목줄, 겁이많고 경계심함
양귀쫑긋. 코갈색. 겁있음/방어적입질/소심/칩유무확인불가. 꼬리단미안됨. 털때탐.
양귀쫑긋. 코갈색. 겁있음/방어적입질/소심/칩유무확인불가. 꼬리단미안됨. 털때탐.
양귀처짐. 코검정. 양후지보행이상/고관절질환 의심. 조금으르렁댐/얌전. 꼬리단미안됨.
양귀처짐. 코검정. 양후지보행이상/고관절질환 의심. 조금으르렁댐/얌전. 꼬리단미안됨.
양귀처짐. 코검정. 양후지보행이상/고관절질환 의심. 조금으르렁댐/얌전. 꼬리단미안됨.
양귀처짐. 코검정. 양후지보행이상/고관절질환 의심. 조금으르렁댐/얌전. 꼬리단미안됨.
양눈눈곱. 코갈색. 부정교합. 전신미용흔적. 살찜. 사람따름. 온순함. 피부질환. 양슬개골 심함.
양눈눈곱. 코갈색. 부정교합. 전신미용흔적. 살찜. 사람따름. 온순함. 피부질환. 양슬개골 심함.
양눈눈곱. 코갈색. 부정교합. 전신미용흔적. 살찜. 사람따름. 온순함. 피부질환. 양슬개골 심함.
양눈눈곱. 코갈색. 부정교합. 전신미용흔적. 살찜. 사람따름. 온순함. 피부질환. 양슬개골 심함.
양눈눈곱. 코갈색. 부정교합. 전신미용흔적. 살찜. 사람따름. 온순함. 피부질환. 양슬개골 심함.
금정 1-114, 양눈 백내장, 미용됨
발견당시 목줄 미착용, 야생화로 인한 경계심 강함
발견당시 목줄 미착용, 야생화로 인한 경계심 강함
경계심 약간 있으나 온순한 편. 한일관 앞에서 발견.
야생성 강함
경계심 심함.
경계심 심하고 예민함
경계심 심하고 예민함
경계심 심하고 예민함
경계심 심하고 예민함
경계함. 공격적임. 꼬리단미안됨. 털때탐.
경계함. 공격적임. 꼬리단미안됨. 털때탐.
양귀쫑긋. 코갈색. 겁/소심/입질. 꼬리단미안됨. 털상태양호.
양귀쫑긋. 코갈색. 겁/소심/입질. 꼬리단미안됨. 털상태양호.
왼귀쫑긋. 오른귀처짐. 코검정. 피부질환. 사나움. 꼬리단미안됨. 털상태불량.
왼귀쫑긋. 오른귀처짐. 코검정. 피부질환. 사나움. 꼬리단미안됨. 털상태불량.
왼귀쫑긋. 오른귀처짐. 코검정. 피부질환. 사나움. 꼬리단미안됨. 털상태불량.
소심하나 사람 잘따름
소심하나 사람 잘따름
소심하나 사람 잘따름
소심하나 사람 잘따름
약간 소심하나 사람 잘따름
약간 소심하나 사람 잘따름
소심함
야생 들개 강아지
야생 들개 강아지
빨간목줄.눈물자국.살짝거친털.유선늘어짐/유두큼.겁많음/방어적입질심함.으르렁댐/짖음.단미안됨.
빨간목줄.눈물자국.살짝거친털.유선늘어짐/유두큼.겁많음/방어적입질심함.으르렁댐/짖음.단미안됨.
빨간목줄.눈물자국.살짝거친털.유선늘어짐/유두큼.겁많음/방어적입질심함.으르렁댐/짖음.단미안됨.
빨간목줄.눈물자국.살짝거친털.유선늘어짐/유두큼.겁많음/방어적입질심함.으르렁댐/짖음.단미안됨.
빨간목줄.눈물자국.살짝거친털.유선늘어짐/유두큼.겁많음/방어적입질심함.으르렁댐/짖음.단미안됨.
양귀반접힘. 코검정. 눈물자국. 겁있음/사람좋아함/활발함/낑낑댐. 꼬리단미안됨. 털때탐.
뒷다리 부상, 6세 추정
1-315번/ 심장사상충 양성
1-315번/ 심장사상충 양성
1-315번/ 심장사상충 양성
배꼽탈장, 구조후 미용, 외동파출소 인계
1017호(관리) 554호(공고) 경계심이 심함.
약한 백내장
등에상처
주황색목걸이/낡은갈색목걸이.털뭉침.도망다님/겁있음/방어적입질/칩유무및중성화여부확인불가.
사나움/진드기 많음
사나움/진드기 많음
사나움/진드기 많음
하늘색/미색 목끈착용,왼쪽눈 백내장있슴
야생화된 유기견의 새끼
야생화된 유기견의 새끼
야생화된 유기견의 새끼
야생화된 유기견의 새끼
야생화된 유기견의 새끼
야생화된 유기견의 새끼
야생화된 유기견의 새끼
야생화된 유기견의 새끼
야생화된 유기견의 새끼
야생화된 유기견의 새끼
야생화된 유기견의 새끼
야생화된 유기견의 새끼
우안없음.좌안각결막염.배수술자국.왼위송곳니부러진듯.꼬리끝털더긺.사람좋아함/활발/살짝낑낑댐.
우안없음.좌안각결막염.배수술자국.왼위송곳니부러진듯.꼬리끝털더긺.사람좋아함/활발/살짝낑낑댐.
우안없음.좌안각결막염.배수술자국.왼위송곳니부러진듯.꼬리끝털더긺.사람좋아함/활발/살짝낑낑댐.
심장사상충 음성
심장사상충 음성
심장사상충 음성
심장사상충 음성
나이많음
경계심 강한아이/ 친해질 시간 필요
아파트내쓰레기처리장에서 발견 피부질환
겁이 많고 피부명이 있슴 밥을 먹지않고 계속 밖을보며 울기만함
어린강아지이며 피부병으로 피부염과 탈모가심함
어린강아지이며 피부병으로 피부염과 탈모가심함
어린강아지이며 피부병으로 피부염과 탈모가심함
흰색반점 또렷한 눈코입 말라뮤트피를이어받은믹스경계심없고입질없음시크한외모가무색할만큼순한댕댕이
흰색반점 또렷한 눈코입 말라뮤트피를이어받은믹스경계심없고입질없음시크한외모가무색할만큼순한댕댕이
포획틀에 잡힘, 목테가 조여서 목에 상처깊음, 아플텐데 치료하는 동안 굉장히 얌전했음
사나움
사나움
사상충 양성, 순함
사상충 양성, 순함
사상충 음성, 경계
몸통위주로 피부질환으로 인하여 긁어서 상처가 심한 상태,순하고 활발함,통통하고 부정교합
몸통위주로 피부질환으로 인하여 긁어서 상처가 심한 상태,순하고 활발함,통통하고 부정교합
몸통위주로 피부질환으로 인하여 긁어서 상처가 심한 상태,순하고 활발함,통통하고 부정교합
몸통위주로 피부질환으로 인하여 긁어서 상처가 심한 상태,순하고 활발함,통통하고 부정교합
옴진드기 추정,브라벡토 복용, 겁이 좀 있는 아이 셋째
옴진드기 추정,브라벡토 복용, 겁이 좀 있는 아이 셋째
옴진드기 추정, 브라벡토 복용, 겁이 좀 많은 아이 둘째
옴진드기 추정, 브라벡토 복용, 겁이 좀 많은 아이 둘째
옴진드기 추정, 브라벡토 복용, 겁이 좀 많은 아이
옴진드기 추정, 브라벡토 복용, 겁이 좀 많은 아이
순함,목줄 리드줄 착용,사상충음성
쉰목소리로짖음.좌후지자꾸들려고함.몸곳곳털뭉침.매우여윔.발자닥습진.칩있음.
쉰목소리로짖음.좌후지자꾸들려고함.몸곳곳털뭉침.매우여윔.발자닥습진.칩있음.
쉰목소리로짖음.좌후지자꾸들려고함.몸곳곳털뭉침.매우여윔.발자닥습진.칩있음.
진드기감염
진드기감염
좌측 슬개골탈구
좌측 슬개골탈구
뒷다리골절의심,온순함,강서구 1-218호
사나움, 들개서식지에서 포획
사나움, 들개서식지에서 포획
치석 조금 있음, 만성 아토피, 말랐음, 알러지사료 급여 요망
서혜부 탈장
털짧게 미용됨,피부병있슴,비만상태
털짧게 미용됨,피부병있슴,비만상태
털짧게 미용됨,피부병있슴,비만상태
(개체관리번호2188)경계심
(개체관리번호2184)경계심
7세 추정, 오른쪽 뒷다리 부상
흰색  빨강색가슴줄착용  입질심함
사나움
사나움
사상충 음성, 경계, 피부 안 좋음
파보 코로나 음성, 디스템퍼 인플루엔저 음성, 구충제 사상충 진드기약 처방, 피부 안 좋음
파보 코로나 음성, 디스템퍼 인플루엔저 음성, 구충제 사상충 진드기약 처방, 피부 안 좋음
파보 코로나 음성, 디스템퍼 인플루엔저 음성, 구충제 사상충 진드기약 처방, 피부 안 좋음
파보 코로나 음성, 디스템퍼 인플루엔저 음성, 구충제 사상충 진드기약 처방, 피부 안 좋음
사상충 양성, 경계
사상충 양성, 경계
다리를 다쳤으며 자견과 같이 발견됨 온순하며 사람을 잘따름
경계심 심함
경계심 심함
왼귀쫑긋/오른귀끝 살짝접힘. 코검정. 앞니 영구치/송곳니 유치. 진드기오염. 으르렁댐/겁많음/소심함.
왼귀쫑긋/오른귀끝 살짝접힘. 코검정. 앞니 영구치/송곳니 유치. 진드기오염. 으르렁댐/겁많음/소심함.
왼귀쫑긋/오른귀끝 살짝접힘. 코검정. 앞니 영구치/송곳니 유치. 진드기오염. 으르렁댐/겁많음/소심함.
왼귀쫑긋/오른귀끝 살짝접힘. 코검정. 앞니 영구치/송곳니 유치. 진드기오염. 으르렁댐/겁많음/소심함.
심장사상충 양성
심장사상충 양성
심장사상충 양성
발견당시 목줄착용, 겁이많으며 경계심이 많아 사람을 잘피함
발견당시 목줄착용, 겁이많으며 경계심이 많아 사람을 잘피함
교통사고로 인한 부상있음
교통사고로 인한 부상있음
교통사고로 인한 부상있음
1-313번/심장사상충 양성
1-313번/심장사상충 양성
1-313번/심장사상충 양성
3마리함께 구조/경계심 강함/친해질 시간 필요/영리하게 생긴 아이들
3마리함께 구조/경계심 강함/친해질 시간 필요/영리하게 생긴 아이들
비만상태
경계심 있음
인평리도로에서 오토바이사고로 오른쪽뒷다리골절 치료하실분 도움요청
인평리도로에서 오토바이사고로 오른쪽뒷다리골절 치료하실분 도움요청
약간경계, 소심하고 겁많음,약간큰귀가 접혔음(비글느낌),쌍커풀진눈이 예쁜아이
사람을 경계하며 임신중
종합 , 코로나 장염, 광견병, 레볼루션, 사상충- 음성
종합 , 코로나 장염, 광견병, 레볼루션, 사상충- 음성
종합 , 코로나 장염, 광견병, 레볼루션, 사상충- 음성
종합 , 코로나 장염, 광견병, 레볼루션, 사상충- 음성
사람에게 공격적이며 덫에 의해 왼쪽 뒷다리에 상처가 심하게 남
사람에게 공격적이며 덫에 의해 왼쪽 뒷다리에 상처가 심하게 남
주황형광색 목줄 착용, 뒷다리 교통사고
주황형광색 목줄 착용, 뒷다리 교통사고
순함,사상충음성

In [17]:
del data_all

In [21]:
data_all["특징"][data_all["특징"].isnull() == True] = 0 # null 값 0으로 만들어주기

In [22]:
for i in range(0, len(data_all.index)):
    
    for j in filters:
        
        try:
            match2 = re.search(data_all.iat[i, 2], j) 
            if match2:
                data_all.at[i, "특징"] == 0
            else:
                pass
        except : pass

In [23]:
data_all

    위치(도) 위치(시군구)                                        특징   품종
0      강원      원주                                            믹스견
1      강원      원주                                         0  믹스견
2      경기      포천     양귀쫑긋. 코주황+검정. 입질/으르렁거림. 꼬리단미안됨. 털때탐.   믹스견
3      경기      포천   양귀쫑긋. 콧등상처. 코갈색. 사나움. 입질. 꼬리단미안됨. 털때탐.   믹스견
4      경기      포천  양귀쫑긋. 코갈+검. 사나움/입질/칩유무확인불가. 꼬리단미안됨. 털때탐.  믹스견
..    ...     ...                                       ...  ...
984    경기      화성                                         0  믹스견
985    경기      화성                                         0  믹스견
986    경기      화성                                         0  믹스견
987    경기      화성                                         0  믹스견
988    경기      화성                                         0  믹스견

[891 rows x 4 columns]

In [16]:
pd.DataFrame(data_all).to_excel('./DATA_ALL.xlsx', index = False)

# 작년도 6-9월 (휴가시즌)

In [24]:
data_last_summer = pd.DataFrame() # dataframe 이름 바꾸기

data_last_summer = data_last_summer.append({    # dataframe 이름 바꾸기
    "위치(도)" : "",
    "위치(시군구)": "",
    "품종" : ""
}, ignore_index = True)

 # dataframe 이름 바꾸기

In [26]:
data_last_summer

  위치(도) 위치(시군구) 품종
0

In [25]:
# 옵션 지정 없이, 브라우저 창 같이 보면서 하려고..
driver = webdriver.Chrome(path)
# 처음에 브라우저 로딩 등 기다림을 위해서 대기..
driver.implicitly_wait(5)
# 화면 크기
driver.maximize_window()

In [29]:
try:
    
    for j in range(1, 82):
        url1 = "https://www.animal.go.kr/front/awtis/protection/protectionList.do?totalCount=824&pageSize=10&boardId=&desertionNo=&menuNo=1000000060&searchSDate=2020-06-05&searchEDate=2020-09-05&searchUprCd=&searchOrgCd=&searchCareRegNo=&searchUpKindCd=417000&searchKindCd=&&page="
        url = url1+str(j)
        driver.get(url) 

        for x in range(1, 10):
            dog_xpath = f'//*[@id="searchList"]/div[4]/ul[2]/li[{x}]/div[1]/a'
            driver.find_element_by_xpath(dog_xpath).click()

            a = driver.page_source
            soup=BeautifulSoup(a, "html.parser")


            species = soup.find("table").find_all("td", class_ = "last")[1].get_text().split("]")[1].strip() # 품종
            location_1 = soup.find("table").find_all("td", class_ = "last")[0].get_text().split("-")[0] #위치 '도' 기준
            location_2 = soup.find("table").find_all("td", class_ = "last")[0].get_text().split("-")[1] # 위치 '시군구' 기준

            data_last_summer.at[(j*10)+(x-1)-10, "품종"] = species
            data_last_summer.at[(j*10)+(x-1)-10, "위치(도)"] = location_1
            data_last_summer.at[(j*10)+(x-1)-10, "위치(시군구)"] = location_2  





            back_path = '//*[@id="sub_con"]/div[2]/a/img'
            driver.find_element_by_xpath(back_path).click() # 목록으로 돌아가기
            
except Exception : 
    pass

In [30]:
data_last_summer

    위치(도) 위치(시군구)   품종
0      경북      경산  믹스견
1      경북      영주  믹스견
2      광주      서구  믹스견
3      전북      완주  말티즈
4      경남     창원3  믹스견
..    ...     ...  ...
804    전남      담양  믹스견
805    경남     창원1  믹스견
806    전북      완주  믹스견
807    경남     창원2  믹스견
808    충남      천안  믹스견

[729 rows x 3 columns]

In [31]:
pd.DataFrame(data_last_summer).to_excel('./data_last_summer.xlsx', index = False)

# 작년도 1-5월 (비휴가시즌)

In [32]:
data_last_year = pd.DataFrame() # dataframe 이름 바꾸기

data_last_year = data_last_year.append({    # dataframe 이름 바꾸기
    "위치(도)" : "",
    "위치(시군구)": "",
    "품종" : ""
}, ignore_index = True)

 # dataframe 이름 바꾸기

In [33]:
try:
    
    for j in range(1, 80):
        url1 = "https://www.animal.go.kr/front/awtis/protection/protectionList.do?totalCount=802&pageSize=10&boardId=&desertionNo=&menuNo=1000000060&searchSDate=2020-01-05&searchEDate=2020-06-05&searchUprCd=&searchOrgCd=&searchCareRegNo=&searchUpKindCd=417000&searchKindCd=&&page="
        url = url1+str(j)
        driver.get(url) 

        for x in range(1, 10):
            dog_xpath = f'//*[@id="searchList"]/div[4]/ul[2]/li[{x}]/div[1]/a'
            driver.find_element_by_xpath(dog_xpath).click()

            a = driver.page_source
            soup=BeautifulSoup(a, "html.parser")


            species = soup.find("table").find_all("td", class_ = "last")[1].get_text().split("]")[1].strip() # 품종
            location_1 = soup.find("table").find_all("td", class_ = "last")[0].get_text().split("-")[0] #위치 '도' 기준
            location_2 = soup.find("table").find_all("td", class_ = "last")[0].get_text().split("-")[1] # 위치 '시군구' 기준

            data_last_year.at[(j*10)+(x-1)-10, "품종"] = species
            data_last_year.at[(j*10)+(x-1)-10, "위치(도)"] = location_1
            data_last_year.at[(j*10)+(x-1)-10, "위치(시군구)"] = location_2  





            back_path = '//*[@id="sub_con"]/div[2]/a/img'
            driver.find_element_by_xpath(back_path).click() # 목록으로 돌아가기
            
except Exception : 
    pass

In [34]:
pd.DataFrame(data_last_year).to_excel('./data_last_year.xlsx', index = False)